Repository DigitalRuby/ExchangeSharp, pull requests merged in 2020-02, with the labels that each got.

#517 fix MemoryStream disposed bug in Websockets
  src/ExchangeSharp/Utility/ClientWebSocket.cs
Labels: bug

#518 added ExchangeAPI.GetExchangeAPIFromClassName()
  src/ExchangeSharp/API/Exchanges/_Base/ExchangeAPI.cs
Labels: enhancement

#521 new NuGet 0.7.0
  README.md
  src/ExchangeSharp.Forms/ExchangeSharp.Forms.csproj
  src/ExchangeSharp/ExchangeSharp.csproj
  src/ExchangeSharp/Properties/AssemblyInfo.cs
  src/ExchangeSharpConsole/ExchangeSharpConsole.csproj
  tests/ExchangeSharpTests/ExchangeSharpTests.csproj
Labels: maintenance

#522 BTSE: add public api
  README.md
  src/ExchangeSharp/API/Exchanges/BTSE/ExchangeBTSEAPI.cs
  src/ExchangeSharp/ExchangeSharp.csproj
Labels: enhancement
