Repository DigitalRuby/ExchangeSharp, pull requests merged in 2020-06, with the labels that each got.

#546 new NuGet 0.7.3
  README.md
  src/ExchangeSharp/ExchangeSharp.csproj
  src/ExchangeSharp/Properties/AssemblyInfo.cs
  src/ExchangeSharpConsole/ExchangeSharpConsole.csproj
  tests/ExchangeSharpTests/ExchangeSharpTests.csproj
Labels: maintenance

#547 Small fixes to BTSE
  src/ExchangeSharp/API/Exchanges/BTSE/ExchangeBTSEAPI.cs
Labels: bug

#548 amount is overridden, extra parameters are copyto payload also. extra…
  src/ExchangeSharp/API/Exchanges/Bitstamp/ExchangeBitstampAPI.cs
Labels: bug, exchange-Bitstamp
