Repository DigitalRuby/ExchangeSharp, pull requests merged in 2020-01, with the labels that each got.

#506 new nuget 0.6.4
  README.md
  global.json
  src/ExchangeSharp.Forms/ExchangeSharp.Forms.csproj
  src/ExchangeSharp/ExchangeSharp.csproj
  src/ExchangeSharp/Properties/AssemblyInfo.cs
  src/ExchangeSharpConsole/ExchangeSharpConsole.csproj
  tests/ExchangeSharpTests/ExchangeSharpTests.csproj
Labels: maintenance

#507 remove nuget creation from ExchangeSharp.Forms
  src/ExchangeSharp.Forms/ExchangeSharp.Forms.csproj
  src/ExchangeSharpConsole/ExchangeSharpConsole.csproj
Labels: maintenance

#509 Bittrex: remove GetHistoricalTradesAsync()
  src/ExchangeSharp/API/Exchanges/Bittrex/ExchangeBittrexAPI.cs
Labels: bug

#511 fixed GetHistoricalTradesAsync/GetRecentTradesAsync() issues
  src/ExchangeSharp/API/Exchanges/BinanceGroup/BinanceGroupCommon.cs
  src/ExchangeSharp/API/Exchanges/BitBank/ExchangeBitBankAPI.cs
  src/ExchangeSharp/API/Exchanges/Bitfinex/ExchangeBitfinexAPI.cs
  src/ExchangeSharp/API/Exchanges/Bitstamp/ExchangeBitstampAPI.cs
  src/ExchangeSharp/API/Exchanges/Bittrex/ExchangeBittrexAPI.cs
  src/ExchangeSharp/API/Exchanges/Coinbase/ExchangeCoinbaseAPI.cs
  src/ExchangeSharp/API/Exchanges/Digifinex/ExchangeDigifinexAPI.cs
  src/ExchangeSharp/API/Exchanges/Gemini/ExchangeGeminiAPI.cs
  src/ExchangeSharp/API/Exchanges/Hitbtc/ExchangeHitbtcAPI.cs
  src/ExchangeSharp/API/Exchanges/Kraken/ExchangeKrakenAPI.cs
  src/ExchangeSharp/API/Exchanges/KuCoin/ExchangeKuCoinAPI.cs
  src/ExchangeSharp/API/Exchanges/LBank/ExchangeLBankAPI.cs
  src/ExchangeSharp/API/Exchanges/Livecoin/ExchangeLivecoinAPI.cs
  src/ExchangeSharp/API/Exchanges/NDAX/ExchangeNDAXAPI.cs
  src/ExchangeSharp/API/Exchanges/OKGroup/OKGroupCommon.cs
  src/ExchangeSharp/API/Exchanges/Poloniex/ExchangePoloniexAPI.cs
  src/ExchangeSharp/API/Exchanges/Yobit/ExchangeYobitAPI.cs
  src/ExchangeSharp/API/Exchanges/_Base/ExchangeAPI.cs
  src/ExchangeSharp/API/Exchanges/_Base/IExchangeAPI.cs
Labels: bug

#513 KuCoin: fix GetRecentTradesAsync() and GetHistoricalTradesAsync()
  src/ExchangeSharp/API/Exchanges/KuCoin/ExchangeKuCoinAPI.cs
Labels: bug, exchange-KuCoin

#515 fix Base/Quote currency ordering in global symbol conversion
  src/ExchangeSharp/API/Exchanges/Bithumb/ExchangeBithumbAPI.cs
  src/ExchangeSharp/API/Exchanges/Kraken/ExchangeKrakenAPI.cs
  src/ExchangeSharp/API/Exchanges/_Base/ExchangeAPI.cs
  src/ExchangeSharp/API/Exchanges/_Base/IExchangeAPI.cs
  tests/ExchangeSharpTests/ExchangeTests.cs
Labels: bug

#516 Console: updated help for export and trade-history
  src/ExchangeSharpConsole/Options/ExportOption.cs
  src/ExchangeSharpConsole/Options/TradeHistoryOption.cs
Labels: maintenance
