Repository DigitalRuby/ExchangeSharp, pull requests merged in 2021-06, with the labels that each got.

#596 Add Candles (OHLC) websocket support in ExchangeAPI
  src/ExchangeSharp/API/Exchanges/_Base/ExchangeAPI.cs
  src/ExchangeSharp/API/Exchanges/_Base/IExchangeAPI.cs
Labels: enhancement

#597 Fixes for Bittrex and Kraken after testing live orders.
  src/ExchangeSharp/API/Common/APIRequestMaker.cs
  src/ExchangeSharp/API/Exchanges/Bittrex/ExchangeBittrexAPI.cs
  src/ExchangeSharp/API/Exchanges/Kraken/ExchangeKrakenAPI.cs
Labels: bug, exchange-Bittrex, exchange-Kraken

#598 Ignore Mac DS_Store
  .gitignore
  src/ExchangeSharp/Traders/MovingAverageCalculator.cs
Labels: maintenance

#601 Bybit: Add FundingRate and OrderBook Support
  src/ExchangeSharp/API/Exchanges/Bybit/ExchangeBybitAPI.cs
  src/ExchangeSharp/Model/ExchangeFunding.cs
Labels: enhancement

#602 new NuGet 0.8.1
  README.md
  src/ExchangeSharp/ExchangeSharp.csproj
  src/ExchangeSharp/Properties/AssemblyInfo.cs
  src/ExchangeSharpConsole/ExchangeSharpConsole.csproj
  tests/ExchangeSharpTests/ExchangeSharpTests.csproj
Labels: maintenance

#603 Feature/kraken private websocket support
  src/ExchangeSharp/API/Common/BaseAPI.cs
  src/ExchangeSharp/API/Exchanges/BL3P/ExchangeBL3PAPI.cs
  src/ExchangeSharp/API/Exchanges/BinanceGroup/BinanceGroupCommon.cs
  src/ExchangeSharp/API/Exchanges/BinanceGroup/ExchangeBinanceDEXAPI.cs
  src/ExchangeSharp/API/Exchanges/BitMEX/ExchangeBitMEXAPI.cs
  src/ExchangeSharp/API/Exchanges/Bitfinex/ExchangeBitfinexAPI.cs
  src/ExchangeSharp/API/Exchanges/Bitstamp/ExchangeBitstampAPI.cs
  src/ExchangeSharp/API/Exchanges/Bybit/ExchangeBybitAPI.cs
  src/ExchangeSharp/API/Exchanges/Coinbase/ExchangeCoinbaseAPI.cs
  src/ExchangeSharp/API/Exchanges/Digifinex/ExchangeDigifinexAPI.cs
  src/ExchangeSharp/API/Exchanges/Gemini/ExchangeGeminiAPI.cs
  src/ExchangeSharp/API/Exchanges/Hitbtc/ExchangeHitbtcAPI.cs
  src/ExchangeSharp/API/Exchanges/Huobi/ExchangeHuobiAPI.cs
  src/ExchangeSharp/API/Exchanges/Kraken/ExchangeKrakenAPI.cs
  src/ExchangeSharp/API/Exchanges/KuCoin/ExchangeKuCoinAPI.cs
  src/ExchangeSharp/API/Exchanges/NDAX/ExchangeNDAXAPI.cs
  src/ExchangeSharp/API/Exchanges/OKGroup/OKGroupCommon.cs
  src/ExchangeSharp/API/Exchanges/Poloniex/ExchangePoloniexAPI.cs
  src/ExchangeSharp/API/Exchanges/ZBcom/ExchangeZBcomAPI.cs
  src/ExchangeSharp/API/Exchanges/_Base/ExchangeAPI.cs
  src/ExchangeSharp/API/Exchanges/_Base/IExchangeAPI.cs
  src/ExchangeSharpConsole/Options/WebSocketsCandesOption.cs
  src/ExchangeSharpConsole/Options/WebSocketsOrderbookOption.cs
  src/ExchangeSharpConsole/Options/WebSocketsPositionsOption.cs
  src/ExchangeSharpConsole/Options/WebSocketsTickersOption.cs
  src/ExchangeSharpConsole/Options/WebSocketsTradesOption.cs
  src/ExchangeSharpConsole/Program.cs
Labels: enhancement
