Repository DigitalRuby/ExchangeSharp, pull requests merged in 2021-08, with the labels that each got.

#620 Fixed market order bug using Order.Price
  src/ExchangeSharp/API/Exchanges/BL3P/ExchangeBL3PAPI.cs
  src/ExchangeSharp/API/Exchanges/BinanceGroup/BinanceGroupCommon.cs
  src/ExchangeSharp/API/Exchanges/Bitfinex/ExchangeBitfinexAPI.cs
  src/ExchangeSharp/API/Exchanges/Bitstamp/ExchangeBitstampAPI.cs
  src/ExchangeSharp/API/Exchanges/Bittrex/ExchangeBittrexAPI.cs
  src/ExchangeSharp/API/Exchanges/Coinbase/ExchangeCoinbaseAPI.cs
  src/ExchangeSharp/API/Exchanges/Huobi/ExchangeHuobiAPI.cs
  src/ExchangeSharp/API/Exchanges/Kraken/ExchangeKrakenAPI.cs
  src/ExchangeSharp/API/Exchanges/OKGroup/OKGroupCommon.cs
  src/ExchangeSharp/API/Exchanges/Poloniex/ExchangePoloniexAPI.cs
  src/ExchangeSharp/Model/ExchangeOrderRequest.cs
  src/ExchangeSharp/Model/ExchangeOrderResult.cs
Labels: bug

#622 Add missing REST methods from ExchangeAPI to IExchangeAPI
  src/ExchangeSharp/API/Exchanges/_Base/ExchangeAPI.cs
  src/ExchangeSharp/API/Exchanges/_Base/IExchangeAPI.cs
Labels: maintenance

#625 Added parsing of kraken order fees
  src/ExchangeSharp/API/Exchanges/Kraken/ExchangeKrakenAPI.cs
Labels: bug

#626 Fix Kraken WS orderbook updates and add checksum support
  src/ExchangeSharp/API/Exchanges/Kraken/ExchangeKrakenAPI.cs
  src/ExchangeSharp/Model/ExchangeOrderBook.cs
Labels: bug, exchange-Kraken

#627 Add simple orderbook merging from updates
  src/ExchangeSharp/Model/ExchangeOrderBook.cs
Labels: enhancement

#628 Add trade count to MarketCandle, and scrape from Kraken Exchange
  src/ExchangeSharp/API/Exchanges/Kraken/ExchangeKrakenAPI.cs
  src/ExchangeSharp/API/Exchanges/_Base/ExchangeAPIExtensions.cs
  src/ExchangeSharp/Model/MarketCandle.cs
Labels: enhancement

#629 Keep order removals in Gemini order book deltas.
  src/ExchangeSharp/API/Exchanges/Gemini/ExchangeGeminiAPI.cs
Labels: bug

#630 Poloniex ParseOrderTrades fix
  src/ExchangeSharp/API/Exchanges/Poloniex/ExchangePoloniexAPI.cs
Labels: bug, exchange-Poloniex

#631 Update BinanceGroup ParseOrder
  src/ExchangeSharp/API/Exchanges/BinanceGroup/BinanceGroupCommon.cs
Labels: bug, exchange-Binance

#632 Add missing properties from BaseAPI to IBaseAPI
  src/ExchangeSharp/API/Common/IBaseAPI.cs
Labels: maintenance

#635 Add setters to IAPIRequestHandler properties
  src/ExchangeSharp/API/Common/IAPIRequestMaker.cs
Labels: maintenance
