Repository DigitalRuby/ExchangeSharp, pull requests merged in 2021-07, with the labels that each got.

#607 change System.Net.HttpWebRequest to System.Net.Http.HttpClient
  src/ExchangeSharp/API/Common/APIRequestMaker.cs
Labels: enhancement

#611 Fixes #610 - Use TryAddWithoutValidation() when setting HTTP headers.
  src/ExchangeSharp/API/Common/APIRequestMaker.cs
  src/ExchangeSharp/API/Common/BaseAPI.cs
Labels: bug

#612 Poloniex OnPlaceOrderAsync improvement.
  src/ExchangeSharp/API/Exchanges/Poloniex/ExchangePoloniexAPI.cs
  tests/ExchangeSharpTests/ExchangePoloniexAPITests.cs
Labels: enhancement, exchange-Poloniex

#616 Poloniex order status fix
  src/ExchangeSharp/API/Exchanges/Poloniex/ExchangePoloniexAPI.cs
Labels: bug, exchange-Poloniex

#618 Better symbol name translation and error detection in KrakenExchange.OnGetTickersAsync()
  src/ExchangeSharp/API/Exchanges/Kraken/ExchangeKrakenAPI.cs
Labels: bug
